# Builds build/preview.html - a single-file, self-contained copy of the app.
# All <link rel="stylesheet"> and <script src="..."> tags referencing local files
# are inlined so the app can run from a single HTML file in the preview panel.
# Referenced assets/ svg files are inlined as data URIs.
# NOTE: keep this file ASCII-only (PowerShell 5.1 reads it with the ANSI codepage).
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$indexPath = Join-Path $root "index.html"
$outDir = Join-Path $root "build"
$outPath = Join-Path $outDir "preview.html"

if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

# Convert an SVG file to a safe data URI. EscapeUriString leaves '(' and ')'
# alone, which breaks unquoted CSS url() tokens - escape those by hand and
# quote the URI in CSS output.
function ConvertTo-SvgDataUri([string]$svgText) {
    $escaped = [uri]::EscapeDataString($svgText)
    $escaped = $escaped.Replace("(", "%28").Replace(")", "%29")
    return "data:image/svg+xml,$escaped"
}

$html = Get-Content $indexPath -Raw -Encoding UTF8

# Inline stylesheet links
$html = [regex]::Replace($html, '<link rel="stylesheet" href="([^"]+)"\s*/?>', {
    param($m)
    $file = Join-Path $root ($m.Groups[1].Value -replace '/', '\')
    $css = Get-Content $file -Raw -Encoding UTF8
    "<style>`n/* === $($m.Groups[1].Value) === */`n$css`n</style>"
})

# Inline scripts
$html = [regex]::Replace($html, '<script src="([^"]+)"></script>', {
    param($m)
    $file = Join-Path $root ($m.Groups[1].Value -replace '/', '\')
    $js = Get-Content $file -Raw -Encoding UTF8
    "<script>`n/* === $($m.Groups[1].Value) === */`n$js`n</script>"
})

# Inline assets/ svg references inside CSS url(...) as quoted data URIs
$cssUrlPattern = 'url\(\s*["'']?(\.\./)?(assets/[^)"'']+)["'']?\s*\)'
$html = [regex]::Replace($html, $cssUrlPattern, {
    param($m)
    $rel = $m.Groups[2].Value
    $file = Join-Path $root ($rel -replace '/', '\')
    if (Test-Path $file) {
        $svg = Get-Content $file -Raw -Encoding UTF8
        $uri = ConvertTo-SvgDataUri $svg
        return "url(`"$uri`")"
    }
    return $m.Value
})

# Inline assets/ svg references inside <img src="..."> as data URIs
$imgPattern = '(<img[^>]*?src=")assets/([^"]+)(")'
$html = [regex]::Replace($html, $imgPattern, {
    param($m)
    $file = Join-Path $root (("assets/" + $m.Groups[2].Value) -replace '/', '\')
    if (Test-Path $file) {
        $svg = Get-Content $file -Raw -Encoding UTF8
        return $m.Groups[1].Value + (ConvertTo-SvgDataUri $svg) + $m.Groups[3].Value
    }
    return $m.Value
})

# Replace favicon link with inline data URI (no external request)
$faviconPath = Join-Path $root "assets\favicon.svg"
if (Test-Path $faviconPath) {
    $fav = Get-Content $faviconPath -Raw -Encoding UTF8
    $favData = ConvertTo-SvgDataUri $fav
    $html = [regex]::Replace($html, '<link rel="icon"[^>]*>', "<link rel=""icon"" href=""$favData"" />")
}

# Banner
$html = "<!-- GENERATED by scripts/build-preview.ps1 - do not edit; edit sources and rebuild. -->`n" + $html

[System.IO.File]::WriteAllText($outPath, $html, (New-Object System.Text.UTF8Encoding $false))
Write-Host "Built $outPath ($([math]::Round((Get-Item $outPath).Length/1KB)) KB)"
