# Marks all spec tasks done and appends an implementation note.
$path = Join-Path $PSScriptRoot "..\.trae\specs\tasks.md"
$c = [IO.File]::ReadAllText($path)
$c = $c.Replace("- **Status**: ``pending``", "- **Status**: ``done``")
$note = @"

---

## Implementation note (2026-09-22)

All 31 tasks implemented and verified in-browser via build/preview.html
(generated by scripts/build-preview.ps1). Highlights: cascade engine bridged to
the data layer (reminders/journal/status side effects fire on every create),
all 13 animal-profile tabs live, 30 report routes, full double-entry finance
(ledger, trial balance, P&L, balance sheet, cash/bank books), 15 typed
quick-entry forms, document center with metadata registry, calendar with
expected-heat windows, and local SVG portrait placeholders replacing the
unreachable remote image endpoint. localStorage access is confined to
js/data/; excluded-domain terms audited to zero hits in UI code.
"@
[System.IO.File]::WriteAllText($path, $c + $note, (New-Object System.Text.UTF8Encoding $false))
Write-Host "tasks.md updated"
